name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout the Private Repository
        uses: actions/checkout@v3
        with:
          repository: Hantex9/easybook-app-refactor
          token: ${{ secrets.EASYBOOK_RELEASE_AUTOMATION_REPO_TOKEN }}
          ref: ${{ github.event.inputs.branch }}
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Decode and Create Certificate
        run: |
          echo "${{ secrets.APPLE_P8 }}" | base64 --decode > certificate.p8

      - name: Build iOS
        env:
          EXPO_APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          EXPO_APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          EXPO_APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          EXPO_APPLE_KEY_PATH: certificate.p8
        run: eas build -p ios --local --non-interactive
